// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Parcial1_API.Data;

#nullable disable

namespace Parcial1_API.Migrations
{
    [DbContext(typeof(AlumnoContext))]
    partial class AlumnoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Parcial1_API.Model.Alumno", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Carrera")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Edad")
                        .HasColumnType("int");

                    b.Property<int>("Matricula")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Alumno");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Carrera = "Ingeniería",
                            Edad = 20,
                            Matricula = 2024001,
                            Nombre = "Ana López"
                        },
                        new
                        {
                            ID = 2,
                            Carrera = "Derecho",
                            Edad = 22,
                            Matricula = 2024002,
                            Nombre = "Luis Pérez"
                        },
                        new
                        {
                            ID = 3,
                            Carrera = "Medicina",
                            Edad = 21,
                            Matricula = 2024003,
                            Nombre = "María Gómez"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
