// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Parcial1_API.Data;

#nullable disable

namespace Parcial1_API.Migrations
{
    [DbContext(typeof(AlumnoContext))]
    partial class AlumnoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Parcial1_API.Model.Alumno", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Carrera")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Edad")
                        .HasColumnType("int");

                    b.Property<int>("Matricula")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Alumno");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Carrera = "Ingeniería",
                            Edad = 20,
                            Matricula = 2024001,
                            Nombre = "Ana López"
                        },
                        new
                        {
                            ID = 2,
                            Carrera = "Derecho",
                            Edad = 22,
                            Matricula = 2024002,
                            Nombre = "Luis Pérez"
                        },
                        new
                        {
                            ID = 3,
                            Carrera = "Medicina",
                            Edad = 21,
                            Matricula = 2024003,
                            Nombre = "María Gómez"
                        },
                        new
                        {
                            ID = 4,
                            Carrera = "Arquitectura",
                            Edad = 23,
                            Matricula = 2024004,
                            Nombre = "Carlos Ruiz"
                        },
                        new
                        {
                            ID = 5,
                            Carrera = "Psicología",
                            Edad = 19,
                            Matricula = 2024005,
                            Nombre = "Sofía Torres"
                        },
                        new
                        {
                            ID = 6,
                            Carrera = "Contaduría",
                            Edad = 24,
                            Matricula = 2024006,
                            Nombre = "Jorge Díaz"
                        },
                        new
                        {
                            ID = 7,
                            Carrera = "Informática",
                            Edad = 20,
                            Matricula = 2024007,
                            Nombre = "Valeria Ramos"
                        },
                        new
                        {
                            ID = 8,
                            Carrera = "Administración",
                            Edad = 22,
                            Matricula = 2024008,
                            Nombre = "Miguel Sánchez"
                        },
                        new
                        {
                            ID = 9,
                            Carrera = "Biología",
                            Edad = 21,
                            Matricula = 2024009,
                            Nombre = "Lucía Navarro"
                        },
                        new
                        {
                            ID = 10,
                            Carrera = "Economía",
                            Edad = 23,
                            Matricula = 2024010,
                            Nombre = "Daniel Herrera"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
